services:
  frontend:
    build:
      context: ./twitter-frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.frontend.rule=Host(`twitter-clone.lukasvanderspiegel.be`)"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      
      - "traefik.http.routers.frontend-api.rule=Host(`twitter-clone.lukasvanderspiegel.be`) && PathPrefix(`/api`)"
      - "traefik.http.routers.frontend-api.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend-api.entrypoints=web,websecure"
      - "traefik.http.routers.frontend-api.service=api-twitter-mean"
      # /api/tweets (router) --> /tweets (backend)
      - "traefik.http.routers.frontend-api.middlewares=strip-api-prefix"
    # vervangen door traefik:
    # ports:
    #   - 80:80

  api:
    build:
      context: ./twitter-api
      dockerfile: Dockerfile
  
  db:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # env_file:
    #   - .env
    volumes:
      - db-data:/data/db

volumes:
  db-data:

networks:
  default:
    name: twitter-mean